movies/urls.py
from django.urls import path
from .views import movie_list, movie_detail

app_name = 'movies'

urlpatterns = [
    path('list/', movie_list, name='movie_list'),
    path('detail/<int:movie_id>/', movie_detail, name='movie_detail'),
]

test_backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('', lambda request: redirect('movies:movie_list'), name='home')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/models.py
# movies/models.py

from django.db import models

class MpaaRating(models.Model):
    type = models.CharField(max_length=10)
    label = models.CharField(max_length=255)

    def __str__(self):
        return self.type

class Genre(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

class Movie(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=255)
    description = models.TextField()
    imgPath = models.ImageField(upload_to='movie_images/')
    duration = models.IntegerField()
    genre = models.ManyToManyField(Genre)
    language = models.CharField(max_length=50)
    
    # MPAA Rating
    mpaaRating = models.ForeignKey(MpaaRating, on_delete=models.CASCADE, default=None)
    
    userRating = models.CharField(max_length=5)

    def __str__(self):
        return self.name

movies/views.py
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from .models import Movie

def movie_list(request):
    query = request.GET.get('q')

    if query:
        movies = Movie.objects.filter(
            Q(name__icontains=query) | 
            Q(description__icontains=query) | 
            Q(language__icontains=query) | 
            Q(genre__name__icontains=query)
        ).distinct()
    else:
        movies = Movie.objects.all()
    print(request.headers.get('x-requested-with'))
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        # If it's an AJAX request, return JSON response
        movie_list_data = [{'id': movie.id, 'name': movie.name, 'imgPath': movie.imgPath.url, 'duration': movie.duration, 'userRating': movie.userRating} for movie in movies]
        return JsonResponse(movie_list_data, safe=False)
    else:
        # If it's a regular request, render the HTML template
        return render(request, 'movies/movie_list.html', {'movies': movies, 'query': query})


def movie_detail(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    return render(request, 'movies/movie_detail.html', {'movie': movie})

movies/templates/movies/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Movie App{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>
<body>

<div class="container mt-5">
    <h1 class="mt-4">Movies Listing @ GV Cinema</h1>
    {% block content %}{% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

movies/templates/movies/movie_detail.html
{% extends 'movies/base.html' %}

{% block title %}{{ movie.name }} - Movie Detail{% endblock %}

{% block content %}
    <a href="{% url 'movies:movie_list' %}" class="btn btn-outline-primary mb-3">Back</a>
    <h4 class="font-weight-bold mb-3">{{ movie.name }}</h4>
    <p>({{ movie.mpaaRating.type }} - {{ movie.mpaaRating.label }})</p>
    <div class="row">
        <div class="col-md-4">
            <img src="{{ movie.imgPath.url }}" alt="{{ movie.name }}" class="img-fluid">
        </div>
        <div class="col-md-8">
            <h2 class="font-weight-bold">{{ movie.name }}</h2>
            <p>{{ movie.duration }} minutes</p>
            <p>Language: {{ movie.language }}</p>
            <p>Genres: {% for genre in movie.genre.all %}{{ genre.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
            <p>MPAA Rating: {{ movie.mpaaRating.type }} - {{ movie.mpaaRating.label }}</p>
            <p>User Rating: {{ movie.userRating }}</p>
            <h4 class="mt-4">Synopsis</h4>
            <p>{{ movie.description }}</p>
        </div>
    </div>
{% endblock %}

movies/templates/movies/movie_list.html
{% extends 'movies/base.html' %}

{% block title %}Movies Listing @ GV Cinema{% endblock %}

{% block content %}
    <input type="text" id="searchInput" placeholder="Search movies ..." class="form-control mt-3 mb-4">

    <h4 class="font-weight-bold mb-3">Popular movies this month</h4>
    <div class="row">
        {% for movie in movies %}
            <div class="col-md-3 mb-4">
                <a href="{% url 'movies:movie_detail' movie.id %}" style="text-decoration: none; color: inherit;">
                    <div class="card border-0">
                        <img src="{{ movie.imgPath.url }}" alt="{{ movie.name }}" class="card-img-top">
                        <div class="card-body">
                            <h5 class="card-title font-weight-bold">{{ movie.name }}</h5>
                            <p class="card-text">{{ movie.duration }} minutes
                                <br/>
                                User rating : {{ movie.userRating }}
                            </p>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>

    <script>
        // Debounce function for keyup events
        function debounce(func, wait) {
            let timeout;
            return function executedFunction(...args) {
                const later = () => {
                    clearTimeout(timeout);
                    func(...args);
                };
                clearTimeout(timeout);
                timeout = setTimeout(later, wait);
            };
        }

        // Function to perform search
        function performSearch() {
            const query = document.getElementById('searchInput').value;
            // Perform your asynchronous search here (e.g., AJAX request)
            // Update the movie list based on the search result
            // For simplicity, let's assume there is an endpoint 'search_movies'
            fetch(`{% url 'movies:movie_list' %}?q=${query}`, {
                method: 'GET',
                headers: {
                "Content-Type":"application/json",
                "Accept": "application/json",
                "x-requested-with": "XMLHttpRequest",
                }
                })
                .then(response => response.json())
                .then(data => {
                    // Update the movies on the page with the search results
                    const moviesContainer = document.querySelector('.row');
                    moviesContainer.innerHTML = data.map(movie => (
                        `<div class="col-md-3 mb-4">
                            <a href="/movies/detail/${movie.id}" style="text-decoration: none; color: inherit;">
                                <div class="card border-0">
                                    <img src="${movie.imgPath}" alt="${movie.name}" class="card-img-top">
                                    <div class="card-body">
                                        <h5 class="card-title font-weight-bold">${movie.name}</h5>
                                        <p class="card-text">${movie.duration} minutes
                                            <br/>
                                            User rating: ${movie.userRating}
                                        </p>
                                    </div>
                                </div>
                            </a>
                        </div>`
                    )).join('');
                })
                .catch(error => console.error('Error:', error));
        }

        // Attach the debounced search function to the keyup event
        document.getElementById('searchInput').addEventListener('keyup', debounce(performSearch, 300));
    </script>
{% endblock %}